### PR TITLE
[WIP] Updating zeromake's codebase to latest FastHub

### LINKED ISSUE #10: Webview scrolling issue
Scrolling on a markdown content isn't fluid. The scroll jump at the start/end of the content

### PR DESCRIPTION
**Pull request by LightDestory**
The codebase should be updated to match 4.7.3 and implements libre improvements.

- [x] 4.6.9
- [x] 4.7.0
- [x] 4.7.1
- [x] 4.7.2
- [x] 4.7.3
- [x] Libre
- [x] FastHub-RE improvements

4.6.9-4.7.3 has been cherrypicked from zeromake, all credtis goes to him :)

Closes #10 #2 #3

### CODE REVIEW

**Comment by zeromake** [comment]
@LightDestory I'm already doing it, however there are still bugs that have not been solved

**Comment by zeromake** [comment]
@LightDestory 
Just completed the code merger of the original warehouse, all manually block to see the difference moved over.
[commit](https://github.com/zeromake/FastHub/commit/89557a88a2e6325bbe42daed0c6c482c6e70b60c)

There are not too many meaningful changes, issues is to add two emoji, I feel that one line can not put down the layout modified to two lines

**Comment by LightDestory** [comment]
> @LightDestory Just completed the code merger of the original warehouse, all manually block to see the difference moved over. [commit](https://github.com/zeromake/FastHub/commit/89557a88a2e6325bbe42daed0c6c482c6e70b60c) by 4.7.3
> 
> There are not too many meaningful changes, issues is to add two emoji, I feel that one line can not put down the layout modified to two lines

You are so fast!

I was planning to do it slowly because I am busy with exams but you did it already :)

Thanks, you speed up this PR.

**Comment by LightDestory** [comment]
Due to the messy commit history this PR has been introduced again with the following:
261e1fcd6bab57579bfcd426a56159971cb7a188
a6ac70d8a1a90149d8ccae4e065d1ee42c5f0c71
c3001872d1db951c955ee015f3b2e93834ce7549
614a1ec0fe8c9a0a54b0cd63ec085805e1b4779d
1e9026227bee4aa1ed3c9de688933ecca63e0f81
3088ac93d3515214b4ca084e230617491f619a46
0a2585e891791059f0cbc5de46bc6786e7eb6193
4e68041472facefec4d665dd7d84801b44dae7a2
628bb63e01f43ec025f5152bdf417c1b6fc1c5a6

**Pull request merged**
